document.getElementById("btn1").addEventListener("click",function(){
    document.body.style.backgroundColor="red";
});
document.getElementById("btn2").addEventListener("click",function(){
    document.body.style.backgroundColor="blue";
});
document.getElementById("btn3").addEventListener("click",function(){
    document.body.style.backgroundColor="green";
});
document.getElementById("btn4").addEventListener("click",function(){
    document.body.style.backgroundColor="white";
});